name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies with Makefile and venv
      run: |
        make install  # This will set up the virtual environment and install dependencies

    - name: Run the Flask application
      run: |
        make run &  # Start the Flask app
        sleep 5     # Give the Flask server some time to start

    - name: Run tests (optional)
      run: |
        echo "No tests implemented yet."
